### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sando21** [MrPeanutButterz/Bitburner#1]
hi there

i get his error when trying to run main.js

SYNTAX ERROR
main.js@home (PID - 2)

The requested module 'Default/config.js' does not provide an export named 'getTotalNetRam' (sorry we can't be more helpful)

**Comment by MrPeanutButterz** [comment]
Hey Sando21,

I had never noticed, but the import is no longer used in the main,js script. You can remove the entire import, and it should work.

If you want to use the function, you can use this import statement:
import { getTotalNetRam } from "./Default/library.js"
